# Generated by Django 4.0.dev20210202203436 on 2021-02-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thoughts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought_title', models.CharField(max_length=200)),
                ('thought_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
